"use server";

import crypto from "crypto";
import { db } from "@/lib/db";
import { blogs, clients, generatedPosts } from "@/lib/db/schema";
import { and, asc, desc, eq, gte, isNotNull, or, sql } from "drizzle-orm";
import { requireAdmin } from "@/lib/auth/helpers";
import {
  generateContent,
  ideateTopic,
  type GenerateOptions,
  type Tone,
} from "@/lib/services/content-generator";
import {
  assignProfileForBlogIfPeptides,
  getStyleProfileForBlog,
} from "@/lib/actions/style-profile-actions";
import { publishPost, type PlatformBlog } from "@/lib/services/platform-client";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface GenerateAndPublishInput {
  blogId: string;
  topic?: string;
  keywords?: string[];
  wordCount?: number;
  tone?: Tone;
  isAutoGenerated?: boolean;
}

export interface GenerateAndPublishResult {
  success: boolean;
  generatedPostId: string;
  status: "published" | "generated" | "failed";
  externalPostId?: string | number;
  externalPostUrl?: string;
  message: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function blogHasCredentials(blog: typeof blogs.$inferSelect): boolean {
  if (blog.platform === "shopify") {
    if (!blog.shopifyStoreUrl) return false;
    // Two auth modes:
    //   legacy_token       — needs shopifyAdminApiToken
    //   client_credentials — needs shopifyClientId + shopifyClientSecret
    // Default to client_credentials when the column is null (matches the DB default).
    const mode = blog.shopifyAuthMode ?? "client_credentials";
    if (mode === "legacy_token") return Boolean(blog.shopifyAdminApiToken);
    return Boolean(blog.shopifyClientId && blog.shopifyClientSecret);
  }
  return Boolean(blog.wpUrl && blog.wpUsername && blog.wpAppPassword);
}

/** Start of the current UTC day (used for the per-day cap). */
function startOfUtcDay(now: Date): Date {
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
}

/**
 * Parse the blogs.posting_frequency varchar as a positive integer = posts per
 * UTC day. Accepts plain numbers ("2") or patterns like "2x per day", "2/day",
 * "2 posts per day". Anything else (e.g. "3x per week") returns null and the
 * caller falls back to posting_frequency_days.
 */
function parsePostsPerDay(value: string | null | undefined): number | null {
  if (!value) return null;
  const trimmed = value.trim();
  if (!trimmed) return null;

  const direct = Number(trimmed);
  if (Number.isInteger(direct) && direct > 0) return direct;

  const match = trimmed.match(/(\d+)\s*(?:x|\/|\s)*(?:posts?\s*)?(?:per\s*)?day/i);
  if (match) {
    const n = parseInt(match[1], 10);
    if (Number.isInteger(n) && n > 0) return n;
  }
  return null;
}

/** The cron runs every 6 hours, so same-day posts are naturally spaced at
 * least this far apart. We also enforce it in code so manual cron pokes can't
 * ship two posts back-to-back. */
const MIN_HOURS_BETWEEN_POSTS = 6;

/**
 * Hard cap on how many blogs a single cron run will publish to. Prevents a
 * single run from monopolizing the function's maxDuration (300s) when many
 * blogs are due at once — the rest get picked up on the next cron run.
 *
 * Each blog takes ~25-35s end-to-end (Claude content + image scene +
 * Nano Banana + scrubber + platform publish). 25 × 30s = 12.5min, but
 * because runGenerateAndPublish is awaited sequentially and the maxDuration
 * is 300s, only ~10 blogs actually finish in one run. The cap below is a
 * soft upper bound that prevents the loop from queuing more work than it
 * can complete.
 */
const MAX_BLOGS_PER_CRON_RUN = Number(
  process.env.MAX_BLOGS_PER_CRON_RUN || "25",
);

/**
 * Pause between consecutive blog runs inside a single cron tick. The
 * end-to-end generate+publish for one blog takes 25-35s, which is plenty
 * of natural spacing — this small extra delay just protects against burst
 * rate-limit pressure on Anthropic / Google AI Studio when multiple blogs
 * happen to finish quickly back-to-back. Configurable via env.
 */
const INTER_BLOG_DELAY_MS = Number(
  process.env.AUTO_PUBLISH_INTER_BLOG_DELAY_MS || "1500",
);

/**
 * Deterministic preferred publishing hour (0-23 UTC) for a blog, derived
 * from its UUID. Same blog ⇒ same hour, forever. This is what spreads
 * publishes across the day so multiple due blogs don't all hit the
 * Shopify / Anthropic / Google APIs in the same minute.
 *
 *   blog A (uuid c26a8…) → hour 9    (publishes at 09:00 UTC on its days)
 *   blog B (uuid f12d3…) → hour 14   (publishes at 14:00 UTC on its days)
 *   blog C (uuid 4a9b2…) → hour 22   (publishes at 22:00 UTC on its days)
 *
 * The cron only considers a blog due once the current hour has reached or
 * passed the blog's preferred hour. Late cron runs (cron paused, server
 * restart, etc.) still catch up — a blog scheduled for 09:00 that the
 * cron sees at 14:00 still gets published, because 14 ≥ 9.
 */
function preferredHourForBlog(blogId: string): number {
  const hex = crypto
    .createHash("sha1")
    .update(blogId)
    .digest("hex")
    .slice(0, 8);
  return parseInt(hex, 16) % 24;
}

/** Reason a blog is or isn't due. The string is what the cron reports. */
type DueDecision =
  | { due: true }
  | { due: false; reason: string };

/**
 * Cadence eligibility — does NOT check the per-client total cap (that needs a
 * separate query, done in runAutoPublishCron).
 *
 * Logic:
 *   - If blogs.posting_frequency parses to a positive integer (= posts/day):
 *     today's published count must be < that number, AND
 *     lastPostVerifiedAt must be >= MIN_HOURS_BETWEEN_POSTS ago.
 *   - Else if blogs.posting_frequency_days is set (e.g. [2,5] = Tue/Fri):
 *     current weekday must be in the array AND no post already published
 *     today AND MIN_HOURS_BETWEEN_POSTS safety floor against the last post.
 *   - Else: not auto-publishable.
 */
/** ISO weekday (1 = Monday … 7 = Sunday) from a Date in UTC. */
function isoWeekdayUtc(d: Date): number {
  const day = d.getUTCDay(); // 0 = Sunday … 6 = Saturday
  return ((day + 6) % 7) + 1; // 1 = Mon … 7 = Sun
}

const WEEKDAY_NAMES = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

function formatWeekdayList(days: number[]): string {
  return days.map((d) => WEEKDAY_NAMES[d - 1] ?? `?${d}`).join(", ");
}

function isBlogDueForPost(
  blog: typeof blogs.$inferSelect,
  todaysPublishedCount: number,
  now: Date = new Date(),
): DueDecision {
  const last = blog.lastPostVerifiedAt;
  const hour = 1000 * 60 * 60;

  const postsPerDay = parsePostsPerDay(blog.postingFrequency);

  if (postsPerDay !== null) {
    if (todaysPublishedCount >= postsPerDay) {
      return {
        due: false,
        reason: `daily cap hit (${todaysPublishedCount}/${postsPerDay} today)`,
      };
    }
    if (last) {
      const hoursSince = (now.getTime() - last.getTime()) / hour;
      if (hoursSince < MIN_HOURS_BETWEEN_POSTS) {
        return {
          due: false,
          reason: `${hoursSince.toFixed(1)}h since last post < ${MIN_HOURS_BETWEEN_POSTS}h interval`,
        };
      }
    }
    return { due: true };
  }

  // postingFrequencyDays is an integer[] of ISO weekdays (e.g. [2,5] = Tue/Fri).
  // Semantics: "publish on these specific weekdays" — once per configured day.
  const configuredDays = Array.isArray(blog.postingFrequencyDays)
    ? blog.postingFrequencyDays
    : null;
  if (configuredDays && configuredDays.length > 0) {
    const today = isoWeekdayUtc(now);

    // 1. Is today one of the configured weekdays?
    if (!configuredDays.includes(today)) {
      return {
        due: false,
        reason: `today is ${WEEKDAY_NAMES[today - 1]}; configured days are [${formatWeekdayList(configuredDays)}]`,
      };
    }

    // 2. Already posted today?
    if (todaysPublishedCount > 0) {
      return {
        due: false,
        reason: `already published today (${todaysPublishedCount} post${todaysPublishedCount === 1 ? "" : "s"})`,
      };
    }

    // 3. Safety floor against rapid-fire posts (cron poke / manual trigger
    //    races).
    if (last) {
      const hoursSince = (now.getTime() - last.getTime()) / hour;
      if (hoursSince < MIN_HOURS_BETWEEN_POSTS) {
        return {
          due: false,
          reason: `${hoursSince.toFixed(1)}h since last post < ${MIN_HOURS_BETWEEN_POSTS}h safety floor`,
        };
      }
    }

    return { due: true };
  }

  return {
    due: false,
    reason: "no cadence configured (set posting_frequency or posting_frequency_days)",
  };
}

async function getRecentTitles(blogId: string, limit = 20): Promise<string[]> {
  const rows = await db
    .select({ title: generatedPosts.title })
    .from(generatedPosts)
    .where(eq(generatedPosts.blogId, blogId))
    .orderBy(desc(generatedPosts.createdAt))
    .limit(limit);
  return rows.map((r) => r.title).filter((t): t is string => Boolean(t));
}

// ─── Core: generate + publish for one blog ──────────────────────────────────

async function runGenerateAndPublish(
  input: GenerateAndPublishInput,
): Promise<GenerateAndPublishResult> {
  // 1. Load blog + client (for niche)
  const [row] = await db
    .select({
      blog: blogs,
      clientNiche: clients.niche,
    })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(eq(blogs.id, input.blogId))
    .limit(1);

  if (!row) throw new Error(`Blog ${input.blogId} not found`);
  const { blog, clientNiche } = row;

  if (!blogHasCredentials(blog)) {
    throw new Error(
      `Blog ${blog.domain} is missing ${blog.platform} credentials — connect the platform first`,
    );
  }

  // 2. Resolve topic + keywords (auto-ideate if not supplied)
  let topic = input.topic?.trim();
  let keywords = input.keywords ?? [];

  if (!topic) {
    const recentTitles = await getRecentTitles(blog.id);
    const ideated = await ideateTopic(clientNiche, recentTitles);
    topic = ideated.topic;
    if (keywords.length === 0) keywords = ideated.keywords;
  }

  if (!topic) throw new Error("Could not resolve a topic to write about");

  // 3. Insert pending row to track the attempt
  const [pending] = await db
    .insert(generatedPosts)
    .values({
      blogId: blog.id,
      clientId: blog.clientId,
      topic,
      keywords,
      status: "generating",
      isAutoGenerated: input.isAutoGenerated ?? false,
    })
    .returning({ id: generatedPosts.id });

  const generatedPostId = pending.id;

  try {
    // 4. Generate content — pull the style profile (peptide blogs only) so
    //    the composer uses the locked skeleton + the scrubber runs. If the
    //    blog predates the style-profile system, lazily assign one before
    //    generating so the first auto-publish gets the full pipeline.
    let styleProfile = await getStyleProfileForBlog(blog.id);
    if (!styleProfile) {
      const r = await assignProfileForBlogIfPeptides(blog.id);
      if (r.success && r.assigned) {
        styleProfile = await getStyleProfileForBlog(blog.id);
      }
    }
    if (styleProfile) {
      console.info(
        `[auto-publish] Using style profile for ${blog.domain}: ` +
          `voice V${styleProfile.voiceId}, skeleton S${styleProfile.skeletonId}, ` +
          `cadence ${styleProfile.cadenceId}, sub-niche ${styleProfile.subNicheId}, ` +
          `strictness=${styleProfile.scrubberStrictness}`,
      );
    } else {
      console.info(
        `[auto-publish] No style profile for ${blog.domain} (niche="${clientNiche ?? "none"}") — using legacy prompt path`,
      );
    }

    const genOpts: GenerateOptions = {
      topic,
      keywords,
      wordCount: input.wordCount ?? 1000,
      tone: input.tone ?? "professional",
      niche: clientNiche,
      seoOptimized: true,
      styleProfile: styleProfile ?? undefined,
    };
    const content = await generateContent(genOpts);

    await db
      .update(generatedPosts)
      .set({
        status: "publishing",
        title: content.title,
        body: content.content,
        excerpt: content.excerpt,
        metaTitle: content.metaTitle,
        metaDescription: content.metaDescription,
        keywords: content.keywords,
        wordCount: content.wordCount,
        seoScore: content.seoScore,
        readabilityScore: content.readabilityScore,
        brandVoiceScore: content.brandVoiceScore,
        tokensUsed: content.tokensUsed,
        costUsd: content.costUsd.toString(),
        scrubberReport: content.scrubberReport ?? null,
        flaggedForReview: content.flaggedForReview ?? false,
        generatedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(generatedPosts.id, generatedPostId));

    // 5. Publish via platform-client (handles WP + Shopify)
    const platformBlog: PlatformBlog = {
      platform: blog.platform,
      wpUrl: blog.wpUrl,
      wpUsername: blog.wpUsername,
      wpAppPassword: blog.wpAppPassword,
      // Shopify — pass *all* auth fields so buildShopifyCreds picks the right
      // mode. Omitting shopifyAuthMode/clientId/clientSecret made client-
      // credentials blogs fail with "Client ID and Client Secret are required".
      shopifyAuthMode: blog.shopifyAuthMode,
      shopifyStoreUrl: blog.shopifyStoreUrl,
      shopifyAdminApiToken: blog.shopifyAdminApiToken,
      shopifyClientId: blog.shopifyClientId,
      shopifyClientSecret: blog.shopifyClientSecret,
    };

    const publish = await publishPost(platformBlog, {
      title: content.title,
      content: content.content,
      excerpt: content.excerpt,
      status: "publish",
      tags: content.keywords,
      featuredImageUrl: content.heroImageUrl, 
    });

    if (!publish.success) {
      await db
        .update(generatedPosts)
        .set({
          status: "generated",
          failureReason: `Publish failed: ${publish.message}`,
          updatedAt: new Date(),
        })
        .where(eq(generatedPosts.id, generatedPostId));

      return {
        success: false,
        generatedPostId,
        status: "generated",
        message: `Generated but publish failed: ${publish.message}`,
      };
    }

    // 6. Mark published, update blog's last-post tracking
    const publishedAt = new Date();
    await db
      .update(generatedPosts)
      .set({
        status: "published",
        externalPostId: publish.postId != null ? String(publish.postId) : null,
        externalPostUrl: publish.postUrl ?? null,
        publishedAt,
        updatedAt: publishedAt,
      })
      .where(eq(generatedPosts.id, generatedPostId));

    await db
      .update(blogs)
      .set({
        lastPostVerifiedAt: publishedAt,
        lastPostTitle: content.title,
        updatedAt: publishedAt,
      })
      .where(eq(blogs.id, blog.id));

    return {
      success: true,
      generatedPostId,
      status: "published",
      externalPostId: publish.postId,
      externalPostUrl: publish.postUrl,
      message: `Published "${content.title}" to ${blog.domain}`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    await db
      .update(generatedPosts)
      .set({
        status: "failed",
        failureReason: message,
        updatedAt: new Date(),
      })
      .where(eq(generatedPosts.id, generatedPostId));

    return {
      success: false,
      generatedPostId,
      status: "failed",
      message,
    };
  }
}

// ─── Public actions ─────────────────────────────────────────────────────────

/** Admin-triggered manual generate-and-publish for a single blog. */
export async function generateAndPublishForBlog(
  input: GenerateAndPublishInput,
): Promise<GenerateAndPublishResult> {
  await requireAdmin();
  return runGenerateAndPublish(input);
}

export interface AutoPublishResult {
  considered: number;
  due: number;
  published: number;
  failed: number;
  skipped: number;
  deferred: number; // due but capped this run; will run next cron tick
  currentHourUtc: number;
  maxPerRun: number;
  results: Array<{
    blogId: string;
    domain: string;
    preferredHour: number;
    status: "published" | "generated" | "failed" | "skipped" | "deferred";
    message: string;
  }>;
}

/**
 * Cron-triggered sweep. Designed for a network of many blogs where multiple
 * blogs may be due on the same day — we don't want them all hitting the
 * publish path at the same moment.
 *
 * Phases:
 *
 *   1. Load all active blogs with cadence configured, joined to client.
 *   2. For each blog, determine eligibility:
 *        a. Client total-posts cap (clients.totalBlogsTarget)
 *        b. Cadence: today's weekday is in postingFrequencyDays AND not
 *           already published today
 *        c. Time-of-day slot: current UTC hour ≥ preferredHourForBlog(blogId).
 *           This spreads publishes naturally across the day — a blog whose
 *           slot is 09:00 UTC waits until the cron sees hour 9, then is
 *           processed at the first available opportunity.
 *        d. Credentials present
 *   3. Sort the eligible queue by lastPostVerifiedAt ASC NULLS FIRST so
 *      the blog that hasn't posted in the longest is processed first
 *      (priority = "most overdue first"). Tie-break by preferred hour.
 *   4. Take the top MAX_BLOGS_PER_CRON_RUN. Anything beyond that is marked
 *      "deferred" and processed on the next cron run — prevents a single
 *      run from monopolizing maxDuration (300s).
 *   5. Process sequentially. Each blog takes ~25-35s end-to-end; running
 *      them in serial avoids API rate-limit contention against Anthropic,
 *      Google AI Studio, Shopify, and WordPress at the same instant.
 *
 * In-memory counters update as we go so subsequent blogs in the same run
 * see correct per-client totals and per-blog daily counts.
 */
export async function runAutoPublishCron(): Promise<AutoPublishResult> {
  const now = new Date();
  const todayStart = startOfUtcDay(now);
  const currentHour = now.getUTCHours();

  // 1. Active blogs with at least one cadence field set. Sort at the DB
  //    layer by lastPostVerifiedAt ASC NULLS FIRST so we can stream
  //    longest-waiting first without an in-memory sort pass.
  const rows = await db
    .select({
      blog: blogs,
      clientNiche: clients.niche,
      clientTarget: clients.totalBlogsTarget,
    })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(
      and(
        eq(blogs.status, "active"),
        or(isNotNull(blogs.postingFrequency), isNotNull(blogs.postingFrequencyDays)),
      ),
    )
    .orderBy(
      sql`${blogs.lastPostVerifiedAt} ASC NULLS FIRST`,
      asc(blogs.id),
    );

  // 2. Per-client + per-blog usage counters.
  const clientCounts = await db
    .select({
      clientId: generatedPosts.clientId,
      n: sql<number>`count(*)::int`,
    })
    .from(generatedPosts)
    .where(eq(generatedPosts.status, "published"))
    .groupBy(generatedPosts.clientId);
  const publishedByClient = new Map(clientCounts.map((r) => [r.clientId, r.n]));

  const blogCountsToday = await db
    .select({
      blogId: generatedPosts.blogId,
      n: sql<number>`count(*)::int`,
    })
    .from(generatedPosts)
    .where(
      and(
        eq(generatedPosts.status, "published"),
        gte(generatedPosts.publishedAt, todayStart),
      ),
    )
    .groupBy(generatedPosts.blogId);
  const publishedTodayByBlog = new Map(blogCountsToday.map((r) => [r.blogId, r.n]));

  // 3. Determine eligibility for each blog. Build the run queue + the
  //    skip list in one pass so the final result reports both.
  interface QueueEntry {
    blog: typeof blogs.$inferSelect;
    clientTarget: number | null;
    preferredHour: number;
    todayCount: number;
    clientCount: number;
  }
  const queue: QueueEntry[] = [];
  const results: AutoPublishResult["results"] = [];
  let skipped = 0;

  for (const { blog, clientTarget } of rows) {
    const preferredHour = preferredHourForBlog(blog.id);
    const todayCount = publishedTodayByBlog.get(blog.id) ?? 0;
    const clientCount = publishedByClient.get(blog.clientId) ?? 0;

    // 3a. Client total cap
    if (clientTarget && clientTarget > 0 && clientCount >= clientTarget) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: `client cap hit (${clientCount}/${clientTarget} total posts)`,
      });
      continue;
    }

    // 3b. Cadence (weekday + daily-cap + min hours)
    const decision = isBlogDueForPost(blog, todayCount, now);
    if (!decision.due) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: decision.reason,
      });
      continue;
    }

    // 3c. Time-of-day slot. Wait until the cron sees the blog's preferred
    //     hour or later. Blocks before-hours publishes; once hour is
    //     reached, the blog is eligible for the rest of the day.
    //
    //     EXCEPTION: blogs that have never published (lastPostVerifiedAt
    //     is null) bypass the slot check on first run. A newly-created
    //     blog shouldn't have to wait until its randomly-assigned slot
    //     hour to get its first post out — that could be up to 23 hours.
    //     From the second post onward the slot applies normally.
    if (blog.lastPostVerifiedAt && currentHour < preferredHour) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: `current hour ${currentHour}h UTC < preferred hour ${preferredHour}h UTC`,
      });
      continue;
    }

    // 3d. Credentials
    if (!blogHasCredentials(blog)) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: `missing ${blog.platform} credentials`,
      });
      continue;
    }

    queue.push({ blog, clientTarget, preferredHour, todayCount, clientCount });
  }

  // 4. Apply per-run cap. Anything beyond the cap is "deferred" — same
  //    blogs will become eligible again on the next cron tick.
  const toRun = queue.slice(0, MAX_BLOGS_PER_CRON_RUN);
  const deferredQueue = queue.slice(MAX_BLOGS_PER_CRON_RUN);
  for (const entry of deferredQueue) {
    results.push({
      blogId: entry.blog.id,
      domain: entry.blog.domain,
      preferredHour: entry.preferredHour,
      status: "deferred",
      message: `over per-run cap (${MAX_BLOGS_PER_CRON_RUN}) — will run on the next cron tick`,
    });
  }

  if (toRun.length > 0) {
    console.info(
      `[auto-publish] hour=${currentHour}h UTC, considered=${rows.length}, eligible=${queue.length}, running=${toRun.length}, deferred=${deferredQueue.length}, skipped=${skipped}`,
    );
    console.info(
      `[auto-publish] run order: ${toRun
        .map(
          (e, i) =>
            `${i + 1}. ${e.blog.domain} (slot=${e.preferredHour}h, lastPost=${e.blog.lastPostVerifiedAt?.toISOString() ?? "never"})`,
        )
        .join(" | ")}`,
    );
  }

  // 5. Process the run queue sequentially. In-memory counters update so
  //    multi-blog clients respect per-client caps within the same run.
  //
  //    A small inter-blog pause (INTER_BLOG_DELAY_MS) gives Anthropic and
  //    Google a moment to release rate-limit budget between heavy
  //    end-to-end pipelines. At sequential 25-35s/blog the natural delay
  //    is already substantial; this is belt-and-suspenders for bursts.
  let published = 0;
  let failed = 0;
  let blogIndex = 0;

  for (const entry of toRun) {
    const { blog, todayCount, clientCount, preferredHour } = entry;

    if (blogIndex > 0) {
      await new Promise((r) => setTimeout(r, INTER_BLOG_DELAY_MS));
    }
    blogIndex++;

    try {
      const result = await runGenerateAndPublish({
        blogId: blog.id,
        isAutoGenerated: true,
      });
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: result.status,
        message: result.message,
      });
      if (result.status === "published") {
        published++;
        publishedTodayByBlog.set(blog.id, todayCount + 1);
        publishedByClient.set(blog.clientId, clientCount + 1);
      } else {
        failed++;
      }
    } catch (error) {
      failed++;
      const message = error instanceof Error ? error.message : "Unknown error";
      console.error(`Auto-publish failed for ${blog.domain}:`, error);
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "failed",
        message,
      });
    }
  }

  return {
    considered: rows.length,
    due: queue.length,
    published,
    failed,
    skipped,
    deferred: deferredQueue.length,
    currentHourUtc: currentHour,
    maxPerRun: MAX_BLOGS_PER_CRON_RUN,
    results,
  };
}