"use server";

import crypto from "crypto";
import { db } from "@/lib/db";
import { blogs, clients, generatedPosts } from "@/lib/db/schema";
import { and, asc, desc, eq, gte, isNotNull, or, sql } from "drizzle-orm";
import { requireAdmin } from "@/lib/auth/helpers";
import {
  generateContent,
  ideateTopic,
  resolvePostLanguage,
  postLanguageForDomain,
  estimateImageCostUsd,
  type GenerateOptions,
  type Tone,
} from "@/lib/services/content-generator";
import {
  assignProfileForBlogIfPeptides,
  getStyleProfileForBlog,
} from "@/lib/actions/style-profile-actions";
import { publishPost, type PlatformBlog } from "@/lib/services/platform-client";
import { verticalForNiche } from "@/lib/content/verticals";
import { pingIndexNowFireAndForget } from "@/lib/services/index-now-pinger";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface GenerateAndPublishInput {
  blogId: string;
  topic?: string;
  keywords?: string[];
  wordCount?: number;
  tone?: Tone;
  isAutoGenerated?: boolean;
}

export interface GenerateAndPublishResult {
  success: boolean;
  generatedPostId: string;
  status: "published" | "generated" | "failed";
  externalPostId?: string | number;
  externalPostUrl?: string;
  message: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function blogHasCredentials(blog: typeof blogs.$inferSelect): boolean {
  if (blog.platform === "shopify") {
    if (!blog.shopifyStoreUrl) return false;
    // Two auth modes:
    //   legacy_token       — needs shopifyAdminApiToken
    //   client_credentials — needs shopifyClientId + shopifyClientSecret
    // Default to client_credentials when the column is null (matches the DB default).
    const mode = blog.shopifyAuthMode ?? "client_credentials";
    if (mode === "legacy_token") return Boolean(blog.shopifyAdminApiToken);
    return Boolean(blog.shopifyClientId && blog.shopifyClientSecret);
  }
  return Boolean(blog.wpUrl && blog.wpUsername && blog.wpAppPassword);
}

/** Start of the current UTC day (used for the per-day cap). */
function startOfUtcDay(now: Date): Date {
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
}

/**
 * Parse the blogs.posting_frequency varchar as a positive integer = posts per
 * UTC day. Accepts plain numbers ("2") or patterns like "2x per day", "2/day",
 * "2 posts per day". Anything else (e.g. "3x per week") returns null and the
 * caller falls back to posting_frequency_days.
 */
function parsePostsPerDay(value: string | null | undefined): number | null {
  if (!value) return null;
  const trimmed = value.trim();
  if (!trimmed) return null;

  const direct = Number(trimmed);
  if (Number.isInteger(direct) && direct > 0) return direct;

  const match = trimmed.match(/(\d+)\s*(?:x|\/|\s)*(?:posts?\s*)?(?:per\s*)?day/i);
  if (match) {
    const n = parseInt(match[1], 10);
    if (Number.isInteger(n) && n > 0) return n;
  }
  return null;
}

/** The cron runs every 6 hours, so same-day posts are naturally spaced at
 * least this far apart. We also enforce it in code so manual cron pokes can't
 * ship two posts back-to-back. */
const MIN_HOURS_BETWEEN_POSTS = 6;

/**
 * Hard cap on how many blogs a single cron run will publish to. Prevents a
 * single run from monopolizing the function's maxDuration (300s) when many
 * blogs are due at once — the rest get picked up on the next cron run.
 *
 * Each blog takes ~25-35s end-to-end (Claude content + image scene +
 * Nano Banana + scrubber + platform publish). 25 × 30s = 12.5min, but
 * because runGenerateAndPublish is awaited sequentially and the maxDuration
 * is 300s, only ~10 blogs actually finish in one run. The cap below is a
 * soft upper bound that prevents the loop from queuing more work than it
 * can complete.
 */
const MAX_BLOGS_PER_CRON_RUN = Number(
  process.env.MAX_BLOGS_PER_CRON_RUN || "50",
);

/**
 * Per-tick concurrency: how many blogs run in parallel inside a single
 * cron tick. Default 3 (safe vs. Anthropic 50 RPM and Google 60 RPM
 * when combined with 4 shards = 12 simultaneous publishes). Clamped to
 * 1..8. Override on the web service via env var.
 */
void process.env.AUTO_PUBLISH_INTER_BLOG_DELAY_MS; // legacy env, no longer read

/**
 * Deterministic preferred publishing hour (0-23 UTC) for a blog, derived
 * from its UUID. Same blog ⇒ same hour, forever. This is what spreads
 * publishes across the day so multiple due blogs don't all hit the
 * Shopify / Anthropic / Google APIs in the same minute.
 *
 *   blog A (uuid c26a8…) → hour 9    (publishes at 09:00 UTC on its days)
 *   blog B (uuid f12d3…) → hour 14   (publishes at 14:00 UTC on its days)
 *   blog C (uuid 4a9b2…) → hour 22   (publishes at 22:00 UTC on its days)
 *
 * The cron only considers a blog due once the current hour has reached or
 * passed the blog's preferred hour. Late cron runs (cron paused, server
 * restart, etc.) still catch up — a blog scheduled for 09:00 that the
 * cron sees at 14:00 still gets published, because 14 ≥ 9.
 */
function preferredHourForBlog(blogId: string): number {
  const hex = crypto
    .createHash("sha1")
    .update(blogId)
    .digest("hex")
    .slice(0, 8);
  return parseInt(hex, 16) % 24;
}

/**
 * Stable shard assignment for a blog — same blog ⇒ same shard, forever.
 * Used to partition the active blog pool across parallel auto-publish
 * cron services. Each service is configured with (shardIndex, shardCount)
 * via query string and only processes blogs where:
 *
 *   shardForBlog(blog.id, shardCount) === shardIndex
 *
 * Uses bytes 8-15 of the SHA1 hex (different than preferredHourForBlog
 * which uses bytes 0-7) so a blog's shard assignment is independent of
 * its hour assignment.
 */
function shardForBlog(blogId: string, shardCount: number): number {
  if (shardCount <= 1) return 0;
  const hex = crypto
    .createHash("sha1")
    .update(blogId)
    .digest("hex")
    .slice(8, 16);
  return parseInt(hex, 16) % shardCount;
}

/** Reason a blog is or isn't due. */
type DueDecision =
  | { due: true }
  | { due: false; reason: string };

/**
 * Cadence eligibility — does NOT check the per-client total cap (that needs a
 * separate query, done in runAutoPublishCron).
 *
 * Logic:
 *   - If blogs.posting_frequency parses to a positive integer (= posts/day):
 *     today's published count must be < that number, AND
 *     lastPostVerifiedAt must be >= MIN_HOURS_BETWEEN_POSTS ago.
 *   - Else if blogs.posting_frequency_days is set (e.g. [2,5] = Tue/Fri):
 *     current weekday must be in the array AND no post already published
 *     today AND MIN_HOURS_BETWEEN_POSTS safety floor against the last post.
 *   - Else: not auto-publishable.
 */
/** ISO weekday (1 = Monday … 7 = Sunday) from a Date in UTC. */
function isoWeekdayUtc(d: Date): number {
  const day = d.getUTCDay(); // 0 = Sunday … 6 = Saturday
  return ((day + 6) % 7) + 1; // 1 = Mon … 7 = Sun
}

const WEEKDAY_NAMES = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

function formatWeekdayList(days: number[]): string {
  return days.map((d) => WEEKDAY_NAMES[d - 1] ?? `?${d}`).join(", ");
}

// daysSinceLastPost + maxGapDaysForWeekdays were used by the catch-up
// path that bypassed the day filter when a blog missed its scheduled
// day. Removed — the platform now enforces a strict day-only policy:
// the only way a blog publishes is if today is in its configured days.

function isBlogDueForPost(
  blog: typeof blogs.$inferSelect,
  todaysPublishedCount: number,
  now: Date = new Date(),
  // The blog's REAL last-publish time, sourced from
  // MAX(generated_posts.published_at WHERE status='published').
  // CRITICAL: do NOT use blog.lastPostVerifiedAt here — that field is
  // reset every 6h by the post-verification cron whenever it confirms
  // live posts, which would make the safety floor think the blog just
  // posted and skip it forever. Only an actual publish through our
  // system advances this timestamp.
  lastPublishedAt: Date | null = null,
): DueDecision {
  const last = lastPublishedAt;
  const hour = 1000 * 60 * 60;

  const postsPerDay = parsePostsPerDay(blog.postingFrequency);
  const configuredDays = Array.isArray(blog.postingFrequencyDays)
    ? blog.postingFrequencyDays
    : null;
  const hasDayFilter = configuredDays !== null && configuredDays.length > 0;

  // PRIORITY: when posting_frequency_days is set, it is THE day filter.
  // The legacy posting_frequency field (parsed by parsePostsPerDay) only
  // owns the schedule when posting_frequency_days is empty. This stops
  // legacy/CSV data with posting_frequency="1" or "2x per day" from
  // bypassing the weekday picker the operator configured in the form.
  if (postsPerDay !== null && !hasDayFilter) {
    if (todaysPublishedCount >= postsPerDay) {
      return {
        due: false,
        reason: `daily cap hit (${todaysPublishedCount}/${postsPerDay} today)`,
      };
    }
    if (last) {
      const hoursSince = (now.getTime() - last.getTime()) / hour;
      if (hoursSince < MIN_HOURS_BETWEEN_POSTS) {
        return {
          due: false,
          reason: `${hoursSince.toFixed(1)}h since last post < ${MIN_HOURS_BETWEEN_POSTS}h interval`,
        };
      }
    }
    return { due: true };
  }

  // postingFrequencyDays is an integer[] of ISO weekdays (e.g. [2,5] = Tue/Fri).
  // Semantics: strict day-only — the blog publishes only when today
  // matches one of the configured weekdays. No catch-up, no bypass,
  // no exceptions. If a scheduled day is missed (cron outage, paused
  // blog, etc.) the blog simply waits for the next matching weekday.
  if (hasDayFilter && configuredDays) {
    const today = isoWeekdayUtc(now);

    // 1. Strict day filter. Today MUST be a configured weekday.
    if (!configuredDays.includes(today)) {
      return {
        due: false,
        reason: `today is ${WEEKDAY_NAMES[today - 1]}; configured days are [${formatWeekdayList(configuredDays)}]`,
      };
    }

    // 2. Already posted today? Block re-publish — one post per
    //    configured day.
    if (todaysPublishedCount > 0) {
      return {
        due: false,
        reason: `already published today (${todaysPublishedCount} post${todaysPublishedCount === 1 ? "" : "s"})`,
      };
    }

    // 3. Safety floor against rapid-fire posts (cron poke / manual
    //    trigger races). Never publish twice within 6 hours, even on
    //    consecutive configured days.
    if (last) {
      const hoursSince = (now.getTime() - last.getTime()) / hour;
      if (hoursSince < MIN_HOURS_BETWEEN_POSTS) {
        return {
          due: false,
          reason: `${hoursSince.toFixed(1)}h since last post < ${MIN_HOURS_BETWEEN_POSTS}h safety floor`,
        };
      }
    }

    return { due: true };
  }

  return {
    due: false,
    reason: "no cadence configured (set posting_frequency or posting_frequency_days)",
  };
}

async function getRecentTitles(blogId: string, limit = 20): Promise<string[]> {
  const rows = await db
    .select({ title: generatedPosts.title })
    .from(generatedPosts)
    .where(eq(generatedPosts.blogId, blogId))
    .orderBy(desc(generatedPosts.createdAt))
    .limit(limit);
  return rows.map((r) => r.title).filter((t): t is string => Boolean(t));
}

/**
 * Pull the most recent published sibling posts on the same blog whose
 * platform URL is known — used by the content generator to weave inline
 * <a href> internal links into the article body. Per the footprint audit,
 * internal linking is the single SEO signal we were leaving on the table.
 */
async function getInternalLinkRefs(
  blogId: string,
  limit = 8,
): Promise<Array<{ title: string; url: string }>> {
  const rows = await db
    .select({
      title: generatedPosts.title,
      url: generatedPosts.externalPostUrl,
    })
    .from(generatedPosts)
    .where(
      and(
        eq(generatedPosts.blogId, blogId),
        eq(generatedPosts.status, "published"),
        isNotNull(generatedPosts.externalPostUrl),
        isNotNull(generatedPosts.title),
      ),
    )
    .orderBy(desc(generatedPosts.publishedAt))
    .limit(limit);
  return rows
    .filter(
      (r): r is { title: string; url: string } =>
        Boolean(r.title) && Boolean(r.url),
    )
    .map((r) => ({ title: r.title, url: r.url }));
}

// ─── Core: generate + publish for one blog ──────────────────────────────────

async function runGenerateAndPublish(
  input: GenerateAndPublishInput,
): Promise<GenerateAndPublishResult> {
  // 1. Load blog + client (for niche)
  const [row] = await db
    .select({
      blog: blogs,
      clientNiche: clients.niche,
    })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(eq(blogs.id, input.blogId))
    .limit(1);

  if (!row) throw new Error(`Blog ${input.blogId} not found`);
  const { blog, clientNiche } = row;

  if (!blogHasCredentials(blog)) {
    throw new Error(
      `Blog ${blog.domain} is missing ${blog.platform} credentials — connect the platform first`,
    );
  }

  // 2. Load (or lazily assign) the blog's locked style profile FIRST so
  //    it can flow into both topic ideation AND article generation.
  //    Without passing the profile into ideateTopic, every peptide
  //    blog's first post defaulted to BPC-157 (the first item in the
  //    generic peptides keyTopics list). The profile gives each blog a
  //    UNIQUE primary-compounds pair to anchor on.
  let styleProfile = await getStyleProfileForBlog(blog.id);
  if (!styleProfile) {
    const r = await assignProfileForBlogIfPeptides(blog.id);
    if (r.success && r.assigned) {
      styleProfile = await getStyleProfileForBlog(blog.id);
    }
  }
  if (styleProfile) {
    console.info(
      `[auto-publish] Using style profile for ${blog.domain}: ` +
        `voice V${styleProfile.voiceId}, skeleton S${styleProfile.skeletonId}, ` +
        `cadence ${styleProfile.cadenceId}, sub-niche ${styleProfile.subNicheId}, ` +
        `strictness=${styleProfile.scrubberStrictness}, ` +
        `primary=${styleProfile.primaryCompounds.join("+")}`,
    );
  } else {
    console.info(
      `[auto-publish] No style profile for ${blog.domain} (niche="${clientNiche ?? "none"}") — using legacy prompt path`,
    );
  }

  // 3. Resolve topic + keywords (auto-ideate if not supplied). Pass the
  //    style profile so the topic anchors on this blog's unique
  //    primary-compounds + locked sub-niche.
  // Resolve the vertical + post language ONCE so the topic and the
  // article share a language. Bilingual (en_fr) verticals coin-flip to
  // one concrete language for this post.
  const verticalForPost = verticalForNiche(clientNiche);
  // TLD policy: .com → English only; .ca + everything else → the
  // vertical's configured language (bilingual verticals alternate per post).
  const postLanguage = postLanguageForDomain(
    verticalForPost?.language,
    blog.domain,
    clientNiche,
  );

  let topic = input.topic?.trim();
  let keywords = input.keywords ?? [];

  if (!topic) {
    const recentTitles = await getRecentTitles(blog.id);
    const ideated = await ideateTopic(clientNiche, recentTitles, {
      verticalKey: verticalForPost?.key ?? null,
      styleProfile: styleProfile ?? undefined,
      language: postLanguage,
    });
    topic = ideated.topic;
    if (keywords.length === 0) keywords = ideated.keywords;
  }

  if (!topic) throw new Error("Could not resolve a topic to write about");

  // 4. Insert pending row to track the attempt
  const [pending] = await db
    .insert(generatedPosts)
    .values({
      blogId: blog.id,
      clientId: blog.clientId,
      topic,
      keywords,
      status: "generating",
      isAutoGenerated: input.isAutoGenerated ?? false,
    })
    .returning({ id: generatedPosts.id });

  const generatedPostId = pending.id;

  try {
    // 5. Generate content using the style profile loaded in step 2.
    //    Resolve vertical so the generator can pull recent news headlines
    //    as external-link sources for non-peptide posts.
    //    Pre-fetch sibling posts on this blog so the generator can weave
    //    internal links into the article (Stage 1 of the footprint audit
    //    fixes — the single biggest SEO signal we were missing).
    const internalLinkRefs = await getInternalLinkRefs(blog.id, 8);

    // Build genOpts as a function so the topic-recovery loop below can
    // reuse it with a fresh ideated topic on failure.
    const buildGenOpts = (t: string, kw: string[]): GenerateOptions => ({
      topic: t,
      keywords: kw,
      wordCount: input.wordCount ?? 1000,
      tone: input.tone ?? "professional",
      niche: clientNiche,
      seoOptimized: true,
      styleProfile: styleProfile ?? undefined,
      verticalKey: verticalForPost?.key ?? null,
      language: postLanguage,
      blogSeed: blog.id,
      internalLinkRefs,
    });

    // Generation with topic-level recovery. Some subjects fail
    // repeatedly — Claude can refuse certain peptide names (returns no
    // text content), or persist in shape-drift even after the inner
    // shape retry. Rather than fail the post, re-ideate a fresh topic
    // that excludes the failing one and try once more.
    const MAX_TOPIC_ATTEMPTS = 2;
    let currentTopic = topic;
    let currentKeywords = keywords;
    let content: Awaited<ReturnType<typeof generateContent>> | undefined;
    const topicFailures: Array<{ topic: string; error: string }> = [];

    for (let attempt = 1; attempt <= MAX_TOPIC_ATTEMPTS; attempt++) {
      try {
        console.info(
          `[runGenerateAndPublish] attempt ${attempt}/${MAX_TOPIC_ATTEMPTS} for ${blog.domain}: "${currentTopic}"`,
        );
        content = await generateContent(
          buildGenOpts(currentTopic, currentKeywords),
        );
        if (attempt > 1) {
          console.info(
            `[runGenerateAndPublish] recovered on attempt ${attempt} with new topic`,
          );
        }
        break;
      } catch (genErr) {
        const msg =
          genErr instanceof Error ? genErr.message : "Generation failed";
        topicFailures.push({ topic: currentTopic, error: msg });
        console.warn(
          `[runGenerateAndPublish] attempt ${attempt} failed for "${currentTopic}": ${msg.slice(0, 200)}`,
        );

        if (attempt === MAX_TOPIC_ATTEMPTS) {
          // Out of budget — rethrow so the outer catch marks the row
          // failed with the combined error message.
          const combined = topicFailures
            .map((a) => `"${a.topic}": ${a.error}`)
            .join(" | ");
          throw new Error(
            `All ${MAX_TOPIC_ATTEMPTS} topic attempts failed — ${combined}`,
          );
        }

        // Re-ideate, excluding the failed topic. If ideation itself
        // throws, fall through to the outer catch.
        const recent = await getRecentTitles(blog.id);
        const newIdea = await ideateTopic(
          clientNiche,
          [currentTopic, ...recent],
          {
            verticalKey: verticalForPost?.key ?? null,
            styleProfile: styleProfile ?? undefined,
            language: postLanguage,
          },
        );
        if (!newIdea.topic || newIdea.topic.trim() === currentTopic.trim()) {
          throw new Error("Re-ideation returned an empty or duplicate topic");
        }
        currentTopic = newIdea.topic;
        currentKeywords =
          newIdea.keywords.length > 0 ? newIdea.keywords : currentKeywords;
        // Reflect the new topic on the pending row so the dashboard
        // shows what the recovery attempt is actually writing about.
        await db
          .update(generatedPosts)
          .set({
            topic: currentTopic,
            keywords: currentKeywords,
            updatedAt: new Date(),
          })
          .where(eq(generatedPosts.id, generatedPostId));
        console.info(
          `[runGenerateAndPublish] re-ideated topic: "${currentTopic}"`,
        );
      }
    }
    if (!content) {
      // Loop guarantees content is set or we throw. Defensive guard.
      throw new Error(
        "Generation loop exited without content (this should be unreachable)",
      );
    }

    // Cost log — per-post breakdown so the operator can spot drift fast.
    {
      const textCost = Number(content.costUsd) || 0;
      const imageCount =
        (content.heroImageUrl ? 1 : 0) + (content.bodyImageUrl ? 1 : 0);
      const perImage = estimateImageCostUsd();
      const imageCost = imageCount * perImage;
      const total = textCost + imageCost;
      console.info(
        `[cost] ${blog.domain}: text=$${textCost.toFixed(4)} ` +
          `(${content.tokensUsed} tok), ` +
          `images=$${imageCost.toFixed(4)} (${imageCount}× @ $${perImage.toFixed(2)}), ` +
          `total=$${total.toFixed(4)}`,
      );
    }

    await db
      .update(generatedPosts)
      .set({
        status: "publishing",
        title: content.title,
        body: content.content,
        excerpt: content.excerpt,
        metaTitle: content.metaTitle,
        metaDescription: content.metaDescription,
        keywords: content.keywords,
        wordCount: content.wordCount,
        seoScore: content.seoScore,
        readabilityScore: content.readabilityScore,
        brandVoiceScore: content.brandVoiceScore,
        tokensUsed: content.tokensUsed,
        costUsd: content.costUsd.toString(),
        scrubberReport: content.scrubberReport ?? null,
        flaggedForReview: content.flaggedForReview ?? false,
        generatedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(generatedPosts.id, generatedPostId));

    // 5. Publish via platform-client (handles WP + Shopify)
    const platformBlog: PlatformBlog = {
      platform: blog.platform,
      wpUrl: blog.wpUrl,
      wpUsername: blog.wpUsername,
      wpAppPassword: blog.wpAppPassword,
      // SEO plugin routes WordPress meta title/description to Yoast vs
      // RankMath at publish time. Detected during connection test.
      seoPlugin: blog.seoPlugin,
      // Shopify — pass *all* auth fields so buildShopifyCreds picks the right
      // mode. Omitting shopifyAuthMode/clientId/clientSecret made client-
      // credentials blogs fail with "Client ID and Client Secret are required".
      shopifyAuthMode: blog.shopifyAuthMode,
      shopifyStoreUrl: blog.shopifyStoreUrl,
      shopifyAdminApiToken: blog.shopifyAdminApiToken,
      shopifyClientId: blog.shopifyClientId,
      shopifyClientSecret: blog.shopifyClientSecret,
    };

    const publish = await publishPost(platformBlog, {
      title: content.title,
      content: content.content,
      excerpt: content.excerpt,
      status: "publish",
      tags: content.keywords,
      featuredImageUrl: content.heroImageUrl,
      metaTitle: content.metaTitle,
      metaDescription: content.metaDescription,
    });

    if (!publish.success) {
      await db
        .update(generatedPosts)
        .set({
          status: "generated",
          failureReason: `Publish failed: ${publish.message}`,
          updatedAt: new Date(),
        })
        .where(eq(generatedPosts.id, generatedPostId));

      return {
        success: false,
        generatedPostId,
        status: "generated",
        message: `Generated but publish failed: ${publish.message}`,
      };
    }

    // 6. Mark published, update blog's last-post tracking
    const publishedAt = new Date();
    await db
      .update(generatedPosts)
      .set({
        status: "published",
        externalPostId: publish.postId != null ? String(publish.postId) : null,
        externalPostUrl: publish.postUrl ?? null,
        publishedAt,
        updatedAt: publishedAt,
      })
      .where(eq(generatedPosts.id, generatedPostId));

    await db
      .update(blogs)
      .set({
        lastPostVerifiedAt: publishedAt,
        lastPostTitle: content.title,
        updatedAt: publishedAt,
      })
      .where(eq(blogs.id, blog.id));

    // 7. Push notification — IndexNow ping covers Bing, Yandex, Seznam,
    //    Naver, Yep, and DuckDuckGo in one POST. Fire-and-forget: the
    //    publish has already succeeded, so a slow/failed engine ping must
    //    not roll back or delay anything. No-op when INDEXNOW_KEY is unset.
    //    The first publish per blog also auto-deploys the IndexNow key
    //    file to the blog's domain via the platform's API (WP REST media
    //    upload / Shopify Pages create) — no manual setup required.
    //    Subsequent publishes hit an in-memory cache.
    //    Google has no IndexNow equivalent and discovers posts via its
    //    natural sitemap crawl (Yoast/RankMath/Shopify defaults).
    if (publish.postUrl) {
      pingIndexNowFireAndForget(blog, publish.postUrl);
    }

    return {
      success: true,
      generatedPostId,
      status: "published",
      externalPostId: publish.postId,
      externalPostUrl: publish.postUrl,
      message: `Published "${content.title}" to ${blog.domain}`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    await db
      .update(generatedPosts)
      .set({
        status: "failed",
        failureReason: message,
        updatedAt: new Date(),
      })
      .where(eq(generatedPosts.id, generatedPostId));

    return {
      success: false,
      generatedPostId,
      status: "failed",
      message,
    };
  }
}

// ─── Public actions ─────────────────────────────────────────────────────────

/** Admin-triggered manual generate-and-publish for a single blog. */
export async function generateAndPublishForBlog(
  input: GenerateAndPublishInput,
): Promise<GenerateAndPublishResult> {
  await requireAdmin();
  return runGenerateAndPublish(input);
}

export interface AutoPublishResult {
  considered: number;
  /** Total active blogs in DB before shard filter (when sharded). */
  totalActiveBlogs?: number;
  /** This service's shard index (0-based). Present only when sharding. */
  shardIndex?: number;
  /** Total parallel shards. Present only when sharding. */
  shardCount?: number;
  due: number;
  published: number;
  failed: number;
  skipped: number;
  deferred: number; // due but capped this run; will run next cron tick
  currentHourUtc: number;
  maxPerRun: number;
  results: Array<{
    blogId: string;
    domain: string;
    preferredHour: number;
    status: "published" | "generated" | "failed" | "skipped" | "deferred";
    message: string;
  }>;
}

/**
 * Cron-triggered sweep. Designed for a network of many blogs where multiple
 * blogs may be due on the same day — we don't want them all hitting the
 * publish path at the same moment.
 *
 * Phases:
 *
 *   1. Load all active blogs with cadence configured, joined to client.
 *   2. For each blog, determine eligibility:
 *        a. Client total-posts cap (clients.totalBlogsTarget)
 *        b. Cadence: today's weekday is in postingFrequencyDays AND not
 *           already published today
 *        c. Time-of-day slot: current UTC hour ≥ preferredHourForBlog(blogId).
 *           This spreads publishes naturally across the day — a blog whose
 *           slot is 09:00 UTC waits until the cron sees hour 9, then is
 *           processed at the first available opportunity.
 *        d. Credentials present
 *   3. Sort the eligible queue by lastPostVerifiedAt ASC NULLS FIRST so
 *      the blog that hasn't posted in the longest is processed first
 *      (priority = "most overdue first"). Tie-break by preferred hour.
 *   4. Take the top MAX_BLOGS_PER_CRON_RUN. Anything beyond that is marked
 *      "deferred" and processed on the next cron run — prevents a single
 *      run from monopolizing maxDuration (300s).
 *   5. Process sequentially. Each blog takes ~25-35s end-to-end; running
 *      them in serial avoids API rate-limit contention against Anthropic,
 *      Google AI Studio, Shopify, and WordPress at the same instant.
 *
 * In-memory counters update as we go so subsequent blogs in the same run
 * see correct per-client totals and per-blog daily counts.
 */
export async function runAutoPublishCron(
  opts: {
    /** This cron service's shard index (0-based). Default 0 = no sharding. */
    shardIndex?: number;
    /** Total number of parallel cron services. Default 1 = no sharding. */
    shardCount?: number;
  } = {},
): Promise<AutoPublishResult> {
  const now = new Date();
  const todayStart = startOfUtcDay(now);
  const currentHour = now.getUTCHours();

  // Sharding params — validated + defaulted. When shardCount<=1 the
  // shard filter is a no-op (every blog is in shard 0).
  const shardCount =
    Number.isInteger(opts.shardCount) && opts.shardCount! > 0
      ? opts.shardCount!
      : 1;
  const shardIndex =
    Number.isInteger(opts.shardIndex) &&
    opts.shardIndex! >= 0 &&
    opts.shardIndex! < shardCount
      ? opts.shardIndex!
      : 0;

  // 1. Active blogs with at least one cadence field set. Sort at the DB
  //    layer by lastPostVerifiedAt ASC NULLS FIRST so we can stream
  //    longest-waiting first without an in-memory sort pass.
  const rows = await db
    .select({
      blog: blogs,
      clientNiche: clients.niche,
      clientTarget: clients.totalBlogsTarget,
    })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(
      and(
        eq(blogs.status, "active"),
        or(isNotNull(blogs.postingFrequency), isNotNull(blogs.postingFrequencyDays)),
      ),
    )
    .orderBy(
      sql`${blogs.lastPostVerifiedAt} ASC NULLS FIRST`,
      asc(blogs.id),
    );

  // 2. Per-client + per-blog usage counters.
  const clientCounts = await db
    .select({
      clientId: generatedPosts.clientId,
      n: sql<number>`count(*)::int`,
    })
    .from(generatedPosts)
    .where(eq(generatedPosts.status, "published"))
    .groupBy(generatedPosts.clientId);
  const publishedByClient = new Map(clientCounts.map((r) => [r.clientId, r.n]));

  const blogCountsToday = await db
    .select({
      blogId: generatedPosts.blogId,
      n: sql<number>`count(*)::int`,
    })
    .from(generatedPosts)
    .where(
      and(
        eq(generatedPosts.status, "published"),
        gte(generatedPosts.publishedAt, todayStart),
      ),
    )
    .groupBy(generatedPosts.blogId);
  const publishedTodayByBlog = new Map(blogCountsToday.map((r) => [r.blogId, r.n]));

  // Per-blog REAL last-publish timestamp = MAX(published_at) over our own
  // published posts. This is the source of truth for the safety floor and
  // the "brand-new blog" check — NOT blogs.lastPostVerifiedAt, which the
  // post-verification cron resets every 6h (and would otherwise make the
  // safety floor permanently skip blogs that haven't actually re-posted).
  const lastPublishedRows = await db
    .select({
      blogId: generatedPosts.blogId,
      lastPublishedAt: sql<Date | null>`max(${generatedPosts.publishedAt})`,
    })
    .from(generatedPosts)
    .where(eq(generatedPosts.status, "published"))
    .groupBy(generatedPosts.blogId);
  const lastPublishedByBlog = new Map(
    lastPublishedRows.map((r) => [
      r.blogId,
      r.lastPublishedAt ? new Date(r.lastPublishedAt) : null,
    ]),
  );

  // 3. Determine eligibility for each blog. Build the run queue + the
  //    skip list in one pass so the final result reports both.
  interface QueueEntry {
    blog: typeof blogs.$inferSelect;
    clientTarget: number | null;
    preferredHour: number;
    todayCount: number;
    clientCount: number;
    lastPublishedAt: Date | null;
  }
  const queue: QueueEntry[] = [];
  const results: AutoPublishResult["results"] = [];
  let skipped = 0;

  // Filter the candidate list to this shard. When shardCount=1 every
  // row passes (no-op). When >1, each blog is in exactly one shard.
  const shardFilteredRows =
    shardCount <= 1
      ? rows
      : rows.filter(
          (r) => shardForBlog(r.blog.id, shardCount) === shardIndex,
        );

  if (shardCount > 1) {
    console.info(
      `[auto-publish] shard ${shardIndex + 1}/${shardCount} — ` +
        `${shardFilteredRows.length} of ${rows.length} active blogs assigned to this shard`,
    );
  }

  for (const { blog, clientTarget } of shardFilteredRows) {
    const preferredHour = preferredHourForBlog(blog.id);
    const todayCount = publishedTodayByBlog.get(blog.id) ?? 0;
    const clientCount = publishedByClient.get(blog.clientId) ?? 0;
    // Real last-publish time from OUR publish history (not the
    // verification timestamp). null = we have never published to this
    // blog through the system.
    const lastPublishedAt = lastPublishedByBlog.get(blog.id) ?? null;

    // 3a. Client total cap
    if (clientTarget && clientTarget > 0 && clientCount >= clientTarget) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: `client total-posts cap hit (${clientCount}/${clientTarget}) — increase clients.totalBlogsTarget to resume`,
      });
      continue;
    }

    // 3b. Cadence (weekday + daily-cap + min hours)
    const decision = isBlogDueForPost(blog, todayCount, now, lastPublishedAt);
    if (!decision.due) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: decision.reason,
      });
      continue;
    }

    // 3c. Time-of-day slot. Wait until the cron sees the blog's preferred
    //     hour or later. Blocks before-hours publishes; once hour is
    //     reached, the blog is eligible for the rest of the day.
    //
    //     EXCEPTION: brand-new blogs (never published through our system)
    //     bypass the slot check on their first eligible weekday so they
    //     don't sit idle for up to 23h waiting for their slot. We use
    //     OUR publish history (lastPublishedAt), NOT lastPostVerifiedAt,
    //     so a blog with pre-existing live posts that the verification
    //     cron stamped still counts as new to the auto-publisher.
    if (lastPublishedAt && currentHour < preferredHour) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: `current hour ${currentHour}h UTC < preferred hour ${preferredHour}h UTC`,
      });
      continue;
    }

    // 3d. Credentials
    if (!blogHasCredentials(blog)) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: `missing ${blog.platform} credentials`,
      });
      continue;
    }

    queue.push({
      blog,
      clientTarget,
      preferredHour,
      todayCount,
      clientCount,
      lastPublishedAt,
    });
  }

  // 4. Sort + apply per-run cap.
  //
  //    Sort priority:
  //      a. lastPostVerifiedAt ASC NULLS FIRST — oldest-waiting
  //         blogs (and brand-new blogs with null) jump the line over
  //         freshly-posted ones.
  //      b. Tie-break by blog UUID for stable ordering.
  //
  //    Anything beyond MAX_BLOGS_PER_CRON_RUN is "deferred" — those
  //    blogs become eligible again on the next cron tick.
  queue.sort((a, b) => {
    // Oldest real-publish first (null = never published → goes first).
    // Uses our publish history, not the verification timestamp.
    const aLast = a.lastPublishedAt?.getTime() ?? 0;
    const bLast = b.lastPublishedAt?.getTime() ?? 0;
    if (aLast !== bLast) return aLast - bLast;
    return a.blog.id.localeCompare(b.blog.id);
  });
  const toRun = queue.slice(0, MAX_BLOGS_PER_CRON_RUN);
  const deferredQueue = queue.slice(MAX_BLOGS_PER_CRON_RUN);
  for (const entry of deferredQueue) {
    results.push({
      blogId: entry.blog.id,
      domain: entry.blog.domain,
      preferredHour: entry.preferredHour,
      status: "deferred",
      message: `over per-run cap (${MAX_BLOGS_PER_CRON_RUN}) — will run on the next cron tick`,
    });
  }

  if (toRun.length > 0) {
    console.info(
      `[auto-publish] hour=${currentHour}h UTC, considered=${rows.length}, eligible=${queue.length}, running=${toRun.length}, deferred=${deferredQueue.length}, skipped=${skipped}`,
    );
    console.info(
      `[auto-publish] run order: ${toRun
        .map(
          (e, i) =>
            `${i + 1}. ${e.blog.domain} (slot=${e.preferredHour}h, lastPublished=${e.lastPublishedAt?.toISOString() ?? "never"})`,
        )
        .join(" | ")}`,
    );
  }

  // 5. Process the run queue with a concurrency-capped worker pool.
  //
  //    Default 3 concurrent publishes per cron tick. With 4 shards
  //    running hourly this gives 12 simultaneous in-flight publishes
  //    across the network — safe vs. Anthropic's 50 RPM (3 Claude
  //    calls/post × 12 = 36 RPM peak) and Google's 60 RPM (2 image
  //    calls/post × 12 = 24 RPM peak).
  //
  //    Override via AUTO_PUBLISH_CONCURRENCY env var on the web service.
  //    Set to 1 to restore old sequential behaviour for debugging.
  //
  //    Per-blog retry: transient errors (rate limits, 5xx, network)
  //    retry once inside the same tick. Permanent errors (validation,
  //    auth) bail immediately.
  //
  //    JS is single-threaded — Map operations are atomic without locks,
  //    so publishedTodayByBlog / publishedByClient updates are safe
  //    even with parallel workers.
  let published = 0;
  let failed = 0;

  const concurrency = Math.max(
    1,
    Math.min(
      8,
      Number(process.env.AUTO_PUBLISH_CONCURRENCY || "3"),
    ),
  );

  async function publishOne(entry: QueueEntry): Promise<void> {
    const { blog, todayCount, clientCount, preferredHour } = entry;
    let lastError: unknown = null;

    // Up to 2 attempts. Sleep 8s between them so a transient Anthropic
    // 429 has time to release budget. The publish action itself has
    // internal retries against Anthropic/Google, so this is the
    // outermost belt + suspenders.
    for (let attempt = 1; attempt <= 2; attempt++) {
      try {
        if (attempt > 1) {
          await new Promise((r) => setTimeout(r, 8000));
        }
        const result = await runGenerateAndPublish({
          blogId: blog.id,
          isAutoGenerated: true,
        });
        results.push({
          blogId: blog.id,
          domain: blog.domain,
          preferredHour,
          status: result.status,
          message: result.message,
        });
        if (result.status === "published") {
          published++;
          publishedTodayByBlog.set(blog.id, todayCount + 1);
          publishedByClient.set(blog.clientId, clientCount + 1);
        } else {
          failed++;
        }
        return;
      } catch (error) {
        lastError = error;
        const msg = error instanceof Error ? error.message.toLowerCase() : "";
        // Non-transient errors (auth, validation, bad config) — give up
        // immediately so we don't waste a retry slot.
        const isTransient =
          msg.includes("rate limit") ||
          msg.includes("429") ||
          msg.includes("503") ||
          msg.includes("504") ||
          msg.includes("timeout") ||
          msg.includes("etimedout") ||
          msg.includes("econnreset") ||
          msg.includes("network") ||
          msg.includes("overloaded");
        if (!isTransient) break;
      }
    }

    failed++;
    const message =
      lastError instanceof Error ? lastError.message : "Unknown error";
    console.error(
      `Auto-publish failed for ${blog.domain} after retry:`,
      lastError,
    );
    results.push({
      blogId: blog.id,
      domain: blog.domain,
      preferredHour,
      status: "failed",
      message,
    });
  }

  let cursor = 0;
  async function worker(): Promise<void> {
    while (true) {
      const i = cursor++;
      if (i >= toRun.length) return;
      await publishOne(toRun[i]);
    }
  }

  console.info(
    `[auto-publish] starting ${toRun.length} blogs with concurrency=${concurrency}`,
  );
  await Promise.all(
    Array.from({ length: Math.min(concurrency, toRun.length) }, () => worker()),
  );

  return {
    // When sharded, "considered" is the count this shard saw after
    // filtering; totalActiveBlogs is the full network size.
    considered: shardCount > 1 ? shardFilteredRows.length : rows.length,
    ...(shardCount > 1
      ? {
          totalActiveBlogs: rows.length,
          shardIndex,
          shardCount,
        }
      : {}),
    due: queue.length,
    published,
    failed,
    skipped,
    deferred: deferredQueue.length,
    currentHourUtc: currentHour,
    maxPerRun: MAX_BLOGS_PER_CRON_RUN,
    results,
  };
}