import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/config";
import { db } from "@/lib/db";
import { blogs, clients, generatedPosts } from "@/lib/db/schema";
import { and, desc, eq, gte } from "drizzle-orm";

/**
 * Recent failed auto-publishes for the admin notifications drawer.
 *
 * Returns the last N generated_posts rows with status='failed' from the
 * last 24h, joined to their blog domain + client name so the admin can
 * see WHICH blog failed and WHY.
 *
 * GET /api/admin/recent-failures?limit=20
 */
export async function GET(request: Request) {
  const session = await getServerSession(authOptions);
  const role = (session?.user as { role?: string } | undefined)?.role;
  if (!session?.user || (role !== "admin" && role !== "super_admin")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const url = new URL(request.url);
  const limit = Math.min(
    Math.max(parseInt(url.searchParams.get("limit") ?? "20", 10), 1),
    100,
  );

  const dayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);

  const rows = await db
    .select({
      id: generatedPosts.id,
      blogId: generatedPosts.blogId,
      domain: blogs.domain,
      clientName: clients.name,
      topic: generatedPosts.topic,
      title: generatedPosts.title,
      failureReason: generatedPosts.failureReason,
      isAutoGenerated: generatedPosts.isAutoGenerated,
      createdAt: generatedPosts.createdAt,
      updatedAt: generatedPosts.updatedAt,
    })
    .from(generatedPosts)
    .leftJoin(blogs, eq(generatedPosts.blogId, blogs.id))
    .leftJoin(clients, eq(generatedPosts.clientId, clients.id))
    .where(
      and(
        eq(generatedPosts.status, "failed"),
        gte(generatedPosts.createdAt, dayAgo),
      ),
    )
    .orderBy(desc(generatedPosts.updatedAt))
    .limit(limit);

  return NextResponse.json({
    total: rows.length,
    failures: rows.map((r) => ({
      id: r.id,
      blogId: r.blogId,
      domain: r.domain ?? "(unknown blog)",
      clientName: r.clientName ?? "(unknown client)",
      topic: r.topic,
      title: r.title,
      failureReason: r.failureReason ?? "(no reason recorded)",
      isAutoGenerated: r.isAutoGenerated ?? false,
      createdAt: r.createdAt,
      updatedAt: r.updatedAt,
    })),
  });
}
