import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/auth/helpers";
import { getClient } from "@/lib/actions/client-actions";
import { getReports, getCostAnalytics } from "@/lib/actions/report-actions";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  StatCard,
  ReportRow,
  fmtUsd,
} from "@/components/reports/report-pieces";
import {
  ArrowLeft,
  Calendar,
  DollarSign,
  FileText,
  Layers,
  Receipt,
} from "lucide-react";

export const dynamic = "force-dynamic";

export default async function ClientReportsPage({
  params,
}: {
  params: { clientId: string };
}) {
  await requireAdmin();
  const { clientId } = params;

  const client = await getClient(clientId).catch(() => null);
  if (!client) notFound();

  const [data, cost] = await Promise.all([
    getReports({ clientId, pageSize: 100 }),
    getCostAnalytics(clientId),
  ]);
  const items = data.reports;
  const publishedCount = items.filter((r) => r.report.visibleToClient).length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <Link href="/reports">
          <Button variant="ghost" size="icon">
            <ArrowLeft className="size-4" />
          </Button>
        </Link>
        <div>
          <h1 className="text-2xl font-bold tracking-tight">{client.name}</h1>
          <p className="text-sm text-muted-foreground">
            {client.niche ? `${client.niche} · ` : ""}
            {data.total} report{data.total === 1 ? "" : "s"} · {publishedCount}{" "}
            published
          </p>
        </div>
      </div>

      {/* Cost analytics for this client */}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          icon={DollarSign}
          tone="green"
          label="Total Spend"
          value={fmtUsd(cost.totalCostUsd)}
          sub="generation cost, all time"
        />
        <StatCard
          icon={Layers}
          tone="blue"
          label="Avg Cost / Blog"
          value={fmtUsd(cost.avgCostPerBlog)}
          sub={`${cost.blogCount} blog${cost.blogCount === 1 ? "" : "s"} generating`}
        />
        <StatCard
          icon={Receipt}
          tone="blue"
          label="Avg Cost / Post"
          value={fmtUsd(cost.avgCostPerPost)}
          sub="text + images"
        />
        <StatCard
          icon={FileText}
          tone="gray"
          label="Posts Generated"
          value={cost.postCount}
          sub="across this client's blogs"
        />
      </div>

      {/* Reports list */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base">Reports</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          {items.length === 0 ? (
            <div className="px-4 py-12 text-center">
              <Calendar className="mx-auto mb-3 size-8 text-muted-foreground/40" />
              <p className="font-medium">No reports yet for this client</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Reports get generated by the monthly cron, or trigger one
                manually from the Reports page.
              </p>
            </div>
          ) : (
            <div className="divide-y">
              {items.map((row) => (
                <ReportRow key={row.report.id} report={row.report} />
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
