"use client";

import { useEffect, useState, useTransition } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";

type FixQueueItem = {
  issue: {
    id: string;
    title: string;
    description: string | null;
    severity: string;
    category: string;
    pageUrl: string | null;
    autoFixable: boolean | null;
    suggestedFix: string | null;
    status: string;
  };
  blogDomain: string;
};

export default function FixQueuePage() {
  const [queue, setQueue] = useState<FixQueueItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [isPending, startTransition] = useTransition();

  useEffect(() => {
    fetch("/api/seo/fix-queue")
      .then((r) => r.json())
      .then(setQueue)
      .catch(() => toast.error("Failed to load fix queue"))
      .finally(() => setLoading(false));
  }, []);

  async function handleApprove(issueId: string) {
    startTransition(async () => {
      const res = await fetch("/api/seo/fix", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ issueId, action: "approve" }),
      });
      if (res.ok) {
        setQueue((q) => q.filter((item) => item.issue.id !== issueId));
        toast.success("Fix approved and queued for execution");
      } else {
        toast.error("Failed to approve fix");
      }
    });
  }

  async function handleDismiss(issueId: string) {
    startTransition(async () => {
      const res = await fetch("/api/seo/fix", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ issueId, action: "dismiss" }),
      });
      if (res.ok) {
        setQueue((q) => q.filter((item) => item.issue.id !== issueId));
        toast.success("Issue dismissed");
      }
    });
  }

  async function handleGenerateFix(issueId: string) {
    startTransition(async () => {
      const res = await fetch("/api/seo/fix/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ issueId }),
      });
      if (res.ok) {
        const data = await res.json();
        setQueue((q) =>
          q.map((item) =>
            item.issue.id === issueId
              ? { ...item, issue: { ...item.issue, suggestedFix: data.fixContent, status: "queued" } }
              : item
          )
        );
        toast.success("Fix content generated by AI");
      } else {
        toast.error("Failed to generate fix");
      }
    });
  }

  const severityOrder = { critical: 0, warning: 1, notice: 2 };
  const sorted = [...queue].sort(
    (a, b) =>
      (severityOrder[a.issue.severity as keyof typeof severityOrder] || 3) -
      (severityOrder[b.issue.severity as keyof typeof severityOrder] || 3)
  );

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">SEO Fix Queue</h1>
        <p className="text-muted-foreground">
          Review and approve SEO fixes across all blogs. {queue.length} issues pending.
        </p>
      </div>

      {loading ? (
        <div className="space-y-4">
          {[1, 2, 3].map((i) => (
            <Card key={i}><CardContent className="h-24 animate-pulse bg-muted" /></Card>
          ))}
        </div>
      ) : sorted.length === 0 ? (
        <Card>
          <CardContent className="text-center py-12 text-muted-foreground">
            No pending issues in the fix queue.
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {sorted.map((item) => (
            <Card key={item.issue.id}>
              <CardContent className="py-4">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1 space-y-1">
                    <div className="flex items-center gap-2">
                      <Badge
                        variant={
                          item.issue.severity === "critical" ? "destructive" :
                          item.issue.severity === "warning" ? "secondary" : "outline"
                        }
                      >
                        {item.issue.severity}
                      </Badge>
                      <Badge variant="outline">{item.issue.category}</Badge>
                      {item.issue.autoFixable && <Badge variant="outline" className="text-green-600">Auto-fixable</Badge>}
                      <span className="text-sm text-muted-foreground">{item.blogDomain}</span>
                    </div>
                    <p className="font-medium">{item.issue.title}</p>
                    {item.issue.pageUrl && (
                      <p className="text-xs text-muted-foreground truncate">{item.issue.pageUrl}</p>
                    )}
                    {item.issue.description && (
                      <p className="text-sm text-muted-foreground">{item.issue.description}</p>
                    )}
                    {item.issue.suggestedFix && (
                      <div className="mt-2 p-2 bg-muted rounded text-sm">
                        <p className="font-medium text-xs mb-1">Suggested Fix:</p>
                        <p>{item.issue.suggestedFix}</p>
                      </div>
                    )}
                  </div>
                  <div className="flex flex-col gap-2">
                    {item.issue.autoFixable && !item.issue.suggestedFix && (
                      <Button size="sm" variant="outline" onClick={() => handleGenerateFix(item.issue.id)} disabled={isPending}>
                        Generate Fix
                      </Button>
                    )}
                    {item.issue.suggestedFix && (
                      <Button size="sm" onClick={() => handleApprove(item.issue.id)} disabled={isPending}>
                        Approve
                      </Button>
                    )}
                    <Button size="sm" variant="ghost" onClick={() => handleDismiss(item.issue.id)} disabled={isPending}>
                      Dismiss
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
